const imagePaths = {
  apple: require("../assets/product_images/apple.png"),
  apples: require("../assets/product_images/apple.png"),
  avodado: require("../assets/product_images/avocado.png"),
  avodados: require("../assets/product_images/avocado.png"),
  carrots: require("../assets/product_images/carrots.png"),
  cereal: require("../assets/product_images/cereal.png"),
  cooking_apples: require("../assets/product_images/apple.png"),
  default: require("../assets/product_images/default.png"),
  grapes: require("../assets/product_images/green_grapes.png"),
  green_grapes: require("../assets/product_images/green_grapes.png"),
  gala_apples: require("../assets/product_images/apple.png"),
  milk: require("../assets/product_images/milk.png"),
  onion: require("../assets/product_images/onion.png"),
  onions: require("../assets/product_images/onion.png"),
  pink_lady_apples: require("../assets/product_images/apple.png"),
  red_grapes: require("../assets/product_images/red_grapes.png"),
  red_onions: require("../assets/product_images/red_onion.png"),
  spring_onion: require("../assets/product_images/spring_onion.png"),
  spring_onions: require("../assets/product_images/spring_onion.png"),
  strawberry: require("../assets/product_images/strawberry.png"),
  strawberries: require("../assets/product_images/strawberry.png"),
  sweet_potatoes: require("../assets/product_images/sweet_potatoes.png"),
  sweet_potato: require("../assets/product_images/sweet_potatoes.png"),
  tomato: require("../assets/product_images/tomatoes.png"),
  tomatoes: require("../assets/product_images/tomatoes.png"),
};
export default imagePaths;